import { extendTheme } from "@chakra-ui/react";

export const theme = extendTheme({
    colors:{
        primary:{
            900:"#1A202C",
            800:"#2D3748",
            700:"#4A5568",
            600:"#718096",
            500:"#A0AEC0",
            400:"#CBD5E0",
            300:"#E2E8F0",
            200:"#EDF2F7",
            100:"#F7FAFC",
        },
        secondary:{
            900:"#2B6CB0",
            800:"#2C5282",
            700:"#2A4365",
            600:"#2C5282",
            500:"#2B6CB0",
            400:"#3182CE",
            300:"#4299E1",
            200:"#63B3ED",
            100:"#90CDF4",
        },
        tertiary:{
            900:"#9B2C2C",
            800:"#C53030",
            700:"#E53E3E",
            600:"#F56565",
            500:"#FC8181",
            400:"#FEB2B2",
            300:"#FED7D7",
            200:"#FFEEEE",
            100:"#FFF5F5",
        }
    },
    fonts:{
        heading:"Work Sans",
        body:"Work Sans",
    },
    components:{
        Button:{
            baseStyle:{
                borderRadius:"lg",
                fontWeight:"bold",
                fontFamily:"work sans",
                _focus:{
                    boxShadow:"none",
                },
            },
            variants:{
                primary:{
                    bg:"primary.900",
                    color:"white",
                    _hover:{
                        bg:"primary.800",
                    }
                },
                secondary:{
                    bg:"secondary.900",
                    color:"white",
                    _hover:{
                        bg:"secondary.800",
                    },
                },
                tertiary:{
                    bg:"tertiary.900",
                    color:"white",
                    _hover:{
                        bg:"tertiary.800",
                    }
                },
            },
            defaultProps:{
                variant:"primary",
            },
        },
        Input:{
            baseStyle:{
                borderRadius:"lg",
                fontWeight:"bold",
                fontFamily:"work sans",
                _focus:{
                    boxShadow:"none",
                },
            },
            variants:{
                primary:{
                    bg:"primary.900",
                    color:"white",
                    _hover:{
                        bg:"primary.800",
                    },
                    _focus:{
                        bg:"primary.800",
                    },
                },
                secondary:{
                    bg:"secondary.900",
                    color:"white",
                    _hover:{
                        bg:"secondary.800",
                    },
                    _focus:{
                        bg:"secondary.800",
                    }
                },
                tertiary:{
                    bg:"tertiary.900",
                    color:"white",
                    _hover:{
                        bg:"tertiary.800",
                    },
                    _focus:{
                        bg:"tertiary.800",
                    }
                },
            },
            defaultProps:{
                variant:"primary",
            }
        },
        Text:{
            baseStyle:{
                fontFamily:"work sans",
            },
            variants:{
                primary:{
                    color:"primary.900",
                },
                secondary:{
                    color:"secondary.900",
                },
                tertiary:{
                    color:"tertiary.900",
                },
            },
            defaultProps:{
                variant:"primary",
            }
        },
        Heading:{
            baseStyle:{
                fontFamily:"work sans",
            },
            variants:{
                primary:{
                    color:"primary.900",
                },
                secondary:{
                    color:"secondary.900",
                },
                tertiary:{
                    color:"tertiary.900",
                },
            },
            defaultProps:{
                variant:"primary",
            }
        },
    }
})
